# Generated by Django 3.2.5 on 2021-08-05 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='table_dubli',
        ),
        migrations.CreateModel(
            name='same_table',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('proxy.table_proxy',),
        ),
    ]
