# Generated by Django 3.2.6 on 2021-08-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('st_id', models.CharField(max_length=10)),
                ('place', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
